name: flutter_http_demo
description: Flutter app with login and document list using http.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.20.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.5.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
